implement StatusModel
Rawenvoys/PdfGenerator pull request #21
Opened 2024-10-09 11:54 UTC by danielbednarz

2024-10-10 21:31 UTC, Rawenvoys requested changes

2024-10-10 21:31 UTC, Rawenvoys commented on Microservices/User/User.Domain/IFinders/IStatusFinder.cs
> +internal interface IStatusFinder
Rozumiem zamysł:

IFindery i IRepository są internal żeby inne projekty aplikacje korzystające z Domain (np. Application albo jeszcze gorzej jak jakiś Client.Web) nie mogły sobie zaimplementować tego interfejsu.....

.... ale! 

Interfejs ten musi być przecież widoczny dla warstwy Infrastracture.

Nie lubię wymagać od kogoś czegoś czego sam nie robiłem, a tylko Żbiku nam o tym wspominał, dlatego też na szybko zrobiłem Sample i o dziwo działa:

Mowa o `InternalsVisibleToAttribute` :
[Documentation: InternalsVisibleToAttribute Klasa](https://learn.microsoft.com/pl-pl/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-8.0)

Użycie:
![image](https://github.com/user-attachments/assets/56589dd7-0281-4613-bb5a-be7bfdb6a87e)

Jeśli jest to project reference z tej samej solucji to nie trzeba podawać ProjectKey

2024-10-10 21:31 UTC, Rawenvoys commented on Microservices/User/User.Domain/IRepositories/IStatusRepository.cs
> +
Dorzucić `InternalsVisibleToAttribute`

**PS: Zapomniałem, że my nie mamy jeszcze utworzonego projektu Infrastracture, ale sprawdziłem i można podać nieistniejący. Kompilacja się nie wywala :)** 

Od razu podaje cały kod:
`[assembly: InternalsVisibleTo("PdfGenerator.User.Infrastracture")]`

2024-10-11 08:38 UTC, Rawenvoys commented on Microservices/User/User.Domain/Enums/Status.cs
> +﻿namespace PdfGenerator.User.Domain.Enums;
A nie ja to jednak jak chorągiewka, zmieniam zdanie xD

2024-11-06 12:22 UTC, danielbednarz commented on Microservices/User/User.Domain/Enums/Status.cs
> +﻿namespace PdfGenerator.User.Domain.Enums;
czyli jak??

2024-12-18 11:39 UTC, Rawenvoys approved these changes

2024-12-18 11:40 UTC, merged